remote_theme: pages-themes/hacker@v0.2.0
title: Github Drama Repo - Updated
description: Github Drama Repo - for all the juicy Github drama!!!
url: "https://neodrama.github.io/github-drama" # the base hostname & protocol for your site
permalink: pretty # use pretty permalinks
livereload: true # enable live reloading
timezone: "America/New_York" # set the timezone for your site
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
- jekyll-feed
- jekyll-archives
- jekyll-language-plugin
- jekyll-algolia
- jekyll-mentions
- jekyll-admin
- jekyll-loading-lazy
