remote_theme: pages-themes/hacker@v0.2.0
title: Internet Archive Upload W/ Metadata Support
description: Internet Archive Upload Action with Metadata Support for GitHub Actions
url: "https://nick2bad4u.github.io/internet-archive-upload" # the base hostname & protocol for your site
permalink: pretty # use pretty permalinks
livereload: true # enable live reloading
timezone: "America/Detroit" # set the timezone for your site
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
- jekyll-feed
- jekyll-archives
- jekyll-language-plugin
- jekyll-algolia
- jekyll-mentions
- jekyll-admin
- jekyll-loading-lazy
